### ISSUE TITLE
It's not possible to set template for python with usuing f-string

### ISSUE THREAD

**Issue by xxxxxxbox** [bmalehorn/vscode-print-it#11]
Hi there. 
Thanx for great extension for VS Code.

The best practice of printing statements in python is using f-strings.
This is the most convenient way.

Example:
`my_var = "test"`
`print(f"{my_var=}")`

The output of this example is:
`my_var='test'`

So I would like to make a template for python with f-string.
If my PrintIt templeate is
`print(f"{{{raw=}}})`
the output for _my_var_ is: 
`print(f"})`

Please fix "PrintIt" so we could create templates with { } inside {{ }}.

**Comment by bmalehorn** [comment]
Hey @xxxxxxbox , thanks for the feedback. I decided to bite the bullet and just fix this bug by fixing the formatter. If you try out the latest version of print it, this configuration:

```json
"print-it.python.template": "print(f'{{{raw}}=}')",
```

On this string:

```python
var + "foo"
```

produces this print statement:
```python
print(f'{var + "foo"=}')
```

Does that work for you?

**Comment by xxxxxxbox** [comment]
Hi @bmalehorn.
Now it works like a charm. Thanx a lot!

One more suggestion.
While testing once I selected my_var with nearest spaces and PrintIt produced the following result:
`print(f'{ my_var =}') `

Due to spaces this statement doesn't work in python.

Not shure if it is a common problem. But adding to PrintIt simple trim / strip  spaces next to "raw" could fix it.

**Comment by bmalehorn** [comment]
> Hi @bmalehorn. Now it works like a charm. Thanx a lot!

Glad it's working well!

> One more suggestion. While testing once I selected my_var with nearest spaces and PrintIt produced the following result: `print(f'{ my_var =}') `
> 
> Due to spaces this statement doesn't work in python.
> 
> Not shure if it is a common problem. But adding to PrintIt simple trim / strip spaces next to "raw" could fix it.

This probably doesn't happen too often, because:
1. most print statements in most languages are not whitespace sensitive
2. If you put the cursor like this: `my_v|ar` where `|` is the cursor then run print-it, it will add a print statement for the current word `my_var`. You don't need need to select `my_var` yourself.

But I can't think of a reason why anyone would want leading / trailing whitespace, so I implemented your suggestion in https://github.com/bmalehorn/vscode-print-it/commit/bd07e7f6e398f44d8437ad3045c8316c1f05d0b5. Whitespace is now trimmed from your selection before printing.

**Comment by xxxxxxbox** [comment]
@bmalehorn, Thanks a lot!

P.S. Auto selection of word works great, but sometimes users need to manualy select part of statement for "printing"

For example:
`var = car.sensors.speed`

Auto selection would select only one of three words - car / sensors / speed
But a user sometimes would like to print:
```
car
car.sensors
car.sensors.speed
```

**Comment by bmalehorn** [comment]
@xxxxxxbox Ah yep that makes sense. I also have to select to print expressions like that.

Closing this ticket as the underlying issue is resolved.
