### ISSUE TITLE
how to escape curly braces `{` ?

### ISSUE THREAD

**Issue by MuhsinFatih** [bmalehorn/vscode-print-it#7]
I've looked at the code and it looks like you're using micromustache package. I've come up with the following, but it won't print the desired output:
```json
"print-it.python.template": "print(f'{{escaped}}: \u007B{{raw}}\u007D')",
```

desired output:
```py
print(f'var: {var}')
```

actual output:
```py
print(var: }')
```

The following works, but that requires a space between curly braces:
```json
"print-it.python.template": "print(f'{{escaped}}: { {{raw}} }')",
```

actual output:
```py
print(f'var: { var }')
```

How do I escape the curly brace wrapping the double curly braces?

**Comment by bmalehorn** [comment]
Hi @MuhsinFatih, thanks for trying out the extension.

I've also played around with this, and unfortunately there doesn't seem to be a way to render brackets other than the workaround you posted. I picked micromustache because it was easy to use and didn't present a security risk - but it looks like it's a bit lacking in features.

Personally the coding style of the print statements isn't too important for me, since I remove all of them before committing.

**Comment by MuhsinFatih** [comment]
@bmalehorn Thanks!
Agreed, I do the same. Though I'm actually using a template to print `logging.debug(f'var: { var }')`. I only wrote the `print` initially to keep the question to simpler :)  
But again it's not really a problem, I was just nerding out with the details :)

**Comment by bmalehorn** [comment]
@MuhsinFatih Bumping this old thread to say: I've updated the formatting in this extension. It now does a simple find & replace of the strings `{{raw}}` and `{{escaped}}`, so it now can render stuff like `{{{raw}}}` correctly. Let me know if you try it out & it doesn't behave as expected.
